window.esdocSearchIndex = [
  [
    "highbrow/src/cortical-column.js~corticalcolumn",
    "class/src/cortical-column.js~CorticalColumn.html",
    "<span>CorticalColumn</span> <span class=\"search-result-import-path\">highbrow/src/cortical-column.js</span>",
    "class"
  ],
  [
    "highbrow/src/highbrow.js~highbrow",
    "class/src/highbrow.js~Highbrow.html",
    "<span>Highbrow</span> <span class=\"search-result-import-path\">highbrow/src/highbrow.js</span>",
    "class"
  ],
  [
    "highbrow/src/enums.js~htmlinktype",
    "variable/index.html#static-variable-HtmLinkType",
    "<span>HtmLinkType</span> <span class=\"search-result-import-path\">highbrow/src/enums.js</span>",
    "variable"
  ],
  [
    "highbrow/src/htm-network.js~htmnetwork",
    "class/src/htm-network.js~HtmNetwork.html",
    "<span>HtmNetwork</span> <span class=\"search-result-import-path\">highbrow/src/htm-network.js</span>",
    "class"
  ],
  [
    "highbrow/src/links.js~htmnetworklink",
    "class/src/links.js~HtmNetworkLink.html",
    "<span>HtmNetworkLink</span> <span class=\"search-result-import-path\">highbrow/src/links.js</span>",
    "class"
  ],
  [
    "highbrow/src/layer.js~layer",
    "class/src/layer.js~Layer.html",
    "<span>Layer</span> <span class=\"search-result-import-path\">highbrow/src/layer.js</span>",
    "class"
  ],
  [
    "highbrow/src/layer.js~minicolumn",
    "class/src/layer.js~MiniColumn.html",
    "<span>MiniColumn</span> <span class=\"search-result-import-path\">highbrow/src/layer.js</span>",
    "class"
  ],
  [
    "highbrow/src/enums.js~minicolumnstate",
    "variable/index.html#static-variable-MiniColumnState",
    "<span>MiniColumnState</span> <span class=\"search-result-import-path\">highbrow/src/enums.js</span>",
    "variable"
  ],
  [
    "highbrow/src/layer.js~neuron",
    "class/src/layer.js~Neuron.html",
    "<span>Neuron</span> <span class=\"search-result-import-path\">highbrow/src/layer.js</span>",
    "class"
  ],
  [
    "highbrow/src/enums.js~neuronstate",
    "variable/index.html#static-variable-NeuronState",
    "<span>NeuronState</span> <span class=\"search-result-import-path\">highbrow/src/enums.js</span>",
    "variable"
  ],
  [
    "highbrow/src/renderable.js~renderable",
    "class/src/renderable.js~Renderable.html",
    "<span>Renderable</span> <span class=\"search-result-import-path\">highbrow/src/renderable.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/cortical-column.js",
    "file/src/cortical-column.js.html",
    "src/cortical-column.js",
    "file"
  ],
  [
    "src/cortical-column.js~corticalcolumn#constructor",
    "class/src/cortical-column.js~CorticalColumn.html#instance-constructor-constructor",
    "src/cortical-column.js~CorticalColumn#constructor",
    "method"
  ],
  [
    "src/cortical-column.js~corticalcolumn#getchildren",
    "class/src/cortical-column.js~CorticalColumn.html#instance-method-getChildren",
    "src/cortical-column.js~CorticalColumn#getChildren",
    "method"
  ],
  [
    "src/cortical-column.js~corticalcolumn#gethtmnetworklinks",
    "class/src/cortical-column.js~CorticalColumn.html#instance-method-getHtmNetworkLinks",
    "src/cortical-column.js~CorticalColumn#getHtmNetworkLinks",
    "method"
  ],
  [
    "src/cortical-column.js~corticalcolumn#getlayers",
    "class/src/cortical-column.js~CorticalColumn.html#instance-method-getLayers",
    "src/cortical-column.js~CorticalColumn#getLayers",
    "method"
  ],
  [
    "src/cortical-column.js~corticalcolumn#getorigin",
    "class/src/cortical-column.js~CorticalColumn.html#instance-method-getOrigin",
    "src/cortical-column.js~CorticalColumn#getOrigin",
    "method"
  ],
  [
    "src/enums.js",
    "file/src/enums.js.html",
    "src/enums.js",
    "file"
  ],
  [
    "src/highbrow.js",
    "file/src/highbrow.js.html",
    "src/highbrow.js",
    "file"
  ],
  [
    "src/highbrow.js~highbrow.createhtmnetwork",
    "class/src/highbrow.js~Highbrow.html#static-method-createHtmNetwork",
    "src/highbrow.js~Highbrow.createHtmNetwork",
    "method"
  ],
  [
    "src/highbrow.js~highbrow.gethtmlinktypes",
    "class/src/highbrow.js~Highbrow.html#static-method-getHtmLinkTypes",
    "src/highbrow.js~Highbrow.getHtmLinkTypes",
    "method"
  ],
  [
    "src/highbrow.js~highbrow.getminicolumnstates",
    "class/src/highbrow.js~Highbrow.html#static-method-getMiniColumnStates",
    "src/highbrow.js~Highbrow.getMiniColumnStates",
    "method"
  ],
  [
    "src/highbrow.js~highbrow.getneuronstates",
    "class/src/highbrow.js~Highbrow.html#static-method-getNeuronStates",
    "src/highbrow.js~Highbrow.getNeuronStates",
    "method"
  ],
  [
    "src/htm-network.js",
    "file/src/htm-network.js.html",
    "src/htm-network.js",
    "file"
  ],
  [
    "src/htm-network.js~htmnetwork#constructor",
    "class/src/htm-network.js~HtmNetwork.html#instance-constructor-constructor",
    "src/htm-network.js~HtmNetwork#constructor",
    "method"
  ],
  [
    "src/htm-network.js~htmnetwork#getchildren",
    "class/src/htm-network.js~HtmNetwork.html#instance-method-getChildren",
    "src/htm-network.js~HtmNetwork#getChildren",
    "method"
  ],
  [
    "src/htm-network.js~htmnetwork#getcorticalcolumns",
    "class/src/htm-network.js~HtmNetwork.html#instance-method-getCorticalColumns",
    "src/htm-network.js~HtmNetwork#getCorticalColumns",
    "method"
  ],
  [
    "src/htm-network.js~htmnetwork#gethtmnetworklinks",
    "class/src/htm-network.js~HtmNetwork.html#instance-method-getHtmNetworkLinks",
    "src/htm-network.js~HtmNetwork#getHtmNetworkLinks",
    "method"
  ],
  [
    "src/htm-network.js~htmnetwork#getorigin",
    "class/src/htm-network.js~HtmNetwork.html#instance-method-getOrigin",
    "src/htm-network.js~HtmNetwork#getOrigin",
    "method"
  ],
  [
    "src/htm-network.js~htmnetwork#update",
    "class/src/htm-network.js~HtmNetwork.html#instance-method-update",
    "src/htm-network.js~HtmNetwork#update",
    "method"
  ],
  [
    "src/layer.js",
    "file/src/layer.js.html",
    "src/layer.js",
    "file"
  ],
  [
    "src/layer.js~layer#constructor",
    "class/src/layer.js~Layer.html#instance-constructor-constructor",
    "src/layer.js~Layer#constructor",
    "method"
  ],
  [
    "src/layer.js~layer#getchildren",
    "class/src/layer.js~Layer.html#instance-method-getChildren",
    "src/layer.js~Layer#getChildren",
    "method"
  ],
  [
    "src/layer.js~layer#getneurons",
    "class/src/layer.js~Layer.html#instance-method-getNeurons",
    "src/layer.js~Layer#getNeurons",
    "method"
  ],
  [
    "src/layer.js~layer#getorigin",
    "class/src/layer.js~Layer.html#instance-method-getOrigin",
    "src/layer.js~Layer#getOrigin",
    "method"
  ],
  [
    "src/layer.js~layer#tostring",
    "class/src/layer.js~Layer.html#instance-method-toString",
    "src/layer.js~Layer#toString",
    "method"
  ],
  [
    "src/layer.js~minicolumn#constructor",
    "class/src/layer.js~MiniColumn.html#instance-constructor-constructor",
    "src/layer.js~MiniColumn#constructor",
    "method"
  ],
  [
    "src/layer.js~minicolumn#getorigin",
    "class/src/layer.js~MiniColumn.html#instance-method-getOrigin",
    "src/layer.js~MiniColumn#getOrigin",
    "method"
  ],
  [
    "src/layer.js~neuron#getchildren",
    "class/src/layer.js~Neuron.html#instance-method-getChildren",
    "src/layer.js~Neuron#getChildren",
    "method"
  ],
  [
    "src/layer.js~neuron#getname",
    "class/src/layer.js~Neuron.html#instance-method-getName",
    "src/layer.js~Neuron#getName",
    "method"
  ],
  [
    "src/layer.js~neuron#getorigin",
    "class/src/layer.js~Neuron.html#instance-method-getOrigin",
    "src/layer.js~Neuron#getOrigin",
    "method"
  ],
  [
    "src/links.js",
    "file/src/links.js.html",
    "src/links.js",
    "file"
  ],
  [
    "src/links.js~htmnetworklink#constructor",
    "class/src/links.js~HtmNetworkLink.html#instance-constructor-constructor",
    "src/links.js~HtmNetworkLink#constructor",
    "method"
  ],
  [
    "src/links.js~htmnetworklink#getchildren",
    "class/src/links.js~HtmNetworkLink.html#instance-method-getChildren",
    "src/links.js~HtmNetworkLink#getChildren",
    "method"
  ],
  [
    "src/links.js~htmnetworklink#getfrom",
    "class/src/links.js~HtmNetworkLink.html#instance-method-getFrom",
    "src/links.js~HtmNetworkLink#getFrom",
    "method"
  ],
  [
    "src/links.js~htmnetworklink#getorigin",
    "class/src/links.js~HtmNetworkLink.html#instance-method-getOrigin",
    "src/links.js~HtmNetworkLink#getOrigin",
    "method"
  ],
  [
    "src/links.js~htmnetworklink#getto",
    "class/src/links.js~HtmNetworkLink.html#instance-method-getTo",
    "src/links.js~HtmNetworkLink#getTo",
    "method"
  ],
  [
    "src/renderable.js",
    "file/src/renderable.js.html",
    "src/renderable.js",
    "file"
  ],
  [
    "src/renderable.js~renderable#constructor",
    "class/src/renderable.js~Renderable.html#instance-constructor-constructor",
    "src/renderable.js~Renderable#constructor",
    "method"
  ],
  [
    "src/renderable.js~renderable#getchildren",
    "class/src/renderable.js~Renderable.html#instance-method-getChildren",
    "src/renderable.js~Renderable#getChildren",
    "method"
  ],
  [
    "src/renderable.js~renderable#getconfig",
    "class/src/renderable.js~Renderable.html#instance-method-getConfig",
    "src/renderable.js~Renderable#getConfig",
    "method"
  ],
  [
    "src/renderable.js~renderable#getname",
    "class/src/renderable.js~Renderable.html#instance-method-getName",
    "src/renderable.js~Renderable#getName",
    "method"
  ],
  [
    "src/renderable.js~renderable#getoffset",
    "class/src/renderable.js~Renderable.html#instance-method-getOffset",
    "src/renderable.js~Renderable#getOffset",
    "method"
  ],
  [
    "src/renderable.js~renderable#getorigin",
    "class/src/renderable.js~Renderable.html#instance-method-getOrigin",
    "src/renderable.js~Renderable#getOrigin",
    "method"
  ],
  [
    "src/renderable.js~renderable#getparent",
    "class/src/renderable.js~Renderable.html#instance-method-getParent",
    "src/renderable.js~Renderable#getParent",
    "method"
  ],
  [
    "src/renderable.js~renderable#getscale",
    "class/src/renderable.js~Renderable.html#instance-method-getScale",
    "src/renderable.js~Renderable#getScale",
    "method"
  ],
  [
    "src/renderable.js~renderable#setoffset",
    "class/src/renderable.js~Renderable.html#instance-method-setOffset",
    "src/renderable.js~Renderable#setOffset",
    "method"
  ],
  [
    "src/renderable.js~renderable#setscale",
    "class/src/renderable.js~Renderable.html#instance-method-setScale",
    "src/renderable.js~Renderable#setScale",
    "method"
  ],
  [
    "src/renderable.js~renderable#tostring",
    "class/src/renderable.js~Renderable.html#instance-method-toString",
    "src/renderable.js~Renderable#toString",
    "method"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ]
]